export const JOHN_DEERE_PRODUCT_CATALOG = [
  {
    name: "Tracteur John Deere (série 5E)",
    price: 3000,
    dailyEarnings: 430,
    cycleDays: 90,
    totalReturn: 38700,
    sortOrder: 1,
    imageUrl: "/john-deere/products/catalog/5e-series-tractor.webp",
  },
  {
    name: "Moissonneuse-batteuse John Deere S770",
    price: 7000,
    dailyEarnings: 1050,
    cycleDays: 90,
    totalReturn: 94500,
    sortOrder: 2,
    imageUrl: "/john-deere/products/catalog/s770-combine.webp",
  },
  {
    name: "Chargeuse sur pneus John Deere 544K",
    price: 17000,
    dailyEarnings: 2700,
    cycleDays: 90,
    totalReturn: 243000,
    sortOrder: 3,
    imageUrl: "/john-deere/products/catalog/544k-loader.webp",
  },
  {
    name: "Presse à balles rondes John Deere 560R",
    price: 45000,
    dailyEarnings: 7650,
    cycleDays: 90,
    totalReturn: 688500,
    sortOrder: 4,
    imageUrl: "/john-deere/products/catalog/560r-round-baler.webp",
  },
  {
    name: "Semoir de précision John Deere 1700",
    price: 110000,
    dailyEarnings: 20000,
    cycleDays: 90,
    totalReturn: 1800000,
    sortOrder: 5,
    imageUrl: "/john-deere/products/catalog/1700-precision-planter.webp",
  },
  {
    name: "Pulvérisateur automoteur John Deere R4030",
    price: 225000,
    dailyEarnings: 43900,
    cycleDays: 90,
    totalReturn: 3951000,
    sortOrder: 6,
    imageUrl: "/john-deere/products/catalog/r4030-sprayer.webp",
  },
  {
    name: "Véhicule utilitaire John Deere Gator XUV 835M",
    price: 430000,
    dailyEarnings: 90500,
    cycleDays: 90,
    totalReturn: 8145000,
    sortOrder: 7,
    imageUrl: "/john-deere/products/catalog/gator-xuv-835m.webp",
  },
  {
    name: "Tondeuse autoportée John Deere ZTrak Z530M",
    price: 900000,
    dailyEarnings: 205000,
    cycleDays: 90,
    totalReturn: 18450000,
    sortOrder: 8,
    imageUrl: "/john-deere/products/catalog/ztrak-z530m.webp",
  },
] as const;

export const JOHN_DEERE_PRODUCT_IMAGE_PATHS = JOHN_DEERE_PRODUCT_CATALOG.map(
  (product) => product.imageUrl,
);